import { Platform } from "react-native";

export const Colors = {
  colorPalette: {
    red: "#B4443E",
    gold: "#A68258",
    blue: "#465D74",
  },
  derived: {
    blueDark: "#2E3D4D",
    blueLight: "#5A7A96",
    redLight: "#D4635D",
    goldLight: "#C9A876",
    white: "#F5F2ED",
    black: "#1A1A1A",
  },
  gameUI: {
    rougeTerre: "#B4443E",
    rougeVif: "#C9524B",
    rougeSombre: "#8B3331",
    orSable: "#A68258",
    orClair: "#D4B896",
    orBrillant: "#E8D5B7",
    bleuNuit: "#465D74",
    bleuProfond: "#2A3B4D",
    bleuAbyssal: "#1A2633",
    bleuSurface: "#566E85",
  },
  background: "#141923",
  foreground: "#F2F2ED",
  card: "#282E3D",
  cardForeground: "#F2F2ED",
  playingCardBackground: "#FEFEFD",
  playingCardDisabledBackground: "#D1D1D1",
  primary: "#C34B44",
  primaryForeground: "#FAFAF9",
  secondary: "#B9966E",
  secondaryForeground: "#FAFAF9",
  muted: "#3D4554",
  mutedForeground: "#A5A5A0",
  accent: "#4D5A6B",
  accentForeground: "#F2F2ED",
  destructive: "#E63946",
  destructiveForeground: "#FAFAF9",
  border: "#4D5A6B",
  input: "#333B4A",
  ring: "#C34B44",
  text: "#F5F2ED",
  tint: "#A68258",
  icon: "#5A7A96",
  tabIconDefault: "#5A7A96",
  tabIconSelected: "#A68258",
};

export const Fonts = Platform.select({
  ios: {
    sans: "system-ui",
    serif: "ui-serif",
    rounded: "ui-rounded",
    mono: "ui-monospace",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded:
      "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
