import { Platform } from "react-native";

export const Colors = {
  colorPalette: {
    red: "#5B1525",
    gold: "#C9A55F",
    blue: "#3A0D18",
  },
  derived: {
    blueDark: "#24090F",
    blueLight: "#5B1525",
    redLight: "#7D1E32",
    goldLight: "#E3C77E",
    white: "#F1E8D6",
    black: "#211712",
  },
  gameUI: {
    rougeTerre: "#5B1525",
    rougeVif: "#7D1E32",
    rougeSombre: "#3A0D18",
    orSable: "#C9A55F",
    orClair: "#E3C77E",
    orBrillant: "#F0D98B",
    bleuNuit: "#3A0D18",
    bleuProfond: "#24090F",
    bleuAbyssal: "#16070B",
    bleuSurface: "#5B1525",
  },
  background: "#16070B",
  foreground: "#F1E8D6",
  card: "#3A0D18",
  cardForeground: "#F1E8D6",
  playingCardBackground: "#F1E8D6",
  playingCardDisabledBackground: "#DED0B8",
  primary: "#7D1E32",
  primaryForeground: "#F1E8D6",
  secondary: "#C9A55F",
  secondaryForeground: "#211712",
  muted: "#5B1525",
  mutedForeground: "#DED0B8",
  accent: "#C9A55F",
  accentForeground: "#211712",
  destructive: "#E63946",
  destructiveForeground: "#F1E8D6",
  border: "#C9A55F",
  input: "#24090F",
  ring: "#E3C77E",
  text: "#F1E8D6",
  tint: "#C9A55F",
  icon: "#C9A55F",
  tabIconDefault: "#A98E5A",
  tabIconSelected: "#E3C77E",
};

export const Fonts = Platform.select({
  ios: {
    sans: "system-ui",
    serif: "ui-serif",
    rounded: "ui-rounded",
    mono: "ui-monospace",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded:
      "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
